[package]
name = "chimera_expand"
version = "0.1.0"
edition = "2021"

[dependencies]
chimera_source = { path = "../chimera_source" }
chimera_term = { path = "../chimera_term" }
chimera_ast = { path = "../chimera_ast" }
chimera_parser = { path = "../chimera_parser" }

[dev-dependencies]
chimera_allocator = { workspace = true }

[benchmarks]
expand_bench = { harness = false }
