[package]
name = "chimera_target"
version = "0.1.0"
edition = "2021"

[dependencies]
chimera_source = { path = "../chimera_source" }
chimera_term = { path = "../chimera_term" }
chimera_ast = { path = "../chimera_ast" }
chimera_expand = { path = "../chimera_expand" }
chimera_module = { path = "../chimera_module" }
[dev-dependencies]
chimera_allocator = { workspace = true }
