[package]
name = "chimera_codegen"
version = "0.1.2"
edition = "2021"

[dependencies]
chimera_core = { path = "../chimera_core" }
chimera_source = { path = "../chimera_source" }
chimera_term = { path = "../chimera_term" }
chimera_ast = { path = "../chimera_ast" }

[dev-dependencies]
criterion = { workspace = true }
chimera_allocator = { workspace = true }
chimera_beam_term = { git = "https://github.com/mjgil-chimerair/chimera-beam", package = "chimera_beam_term" }

[benchmarks]
codegen_bench = { harness = true }
